-- =====================================================================
-- Smart Clinic Management System - MySQL schema
-- Database: cms
--
-- The table and column names match what Spring Data JPA generates from
-- the entity classes, so running this script by hand and letting
-- Hibernate manage the schema produce the same structure.
-- =====================================================================

CREATE DATABASE IF NOT EXISTS cms;
USE cms;

DROP TABLE IF EXISTS doctor_available_times;
DROP TABLE IF EXISTS appointment;
DROP TABLE IF EXISTS doctor;
DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS admin;

-- ---------------------------------------------------------------------
-- admin: portal operators. They log in by username, not email.
-- ---------------------------------------------------------------------
CREATE TABLE admin (
    id       BIGINT       NOT NULL AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_admin_username (username)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- patient
-- ---------------------------------------------------------------------
CREATE TABLE patient (
    id       BIGINT       NOT NULL AUTO_INCREMENT,
    name     VARCHAR(100) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone    VARCHAR(10)  NOT NULL,
    address  VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_patient_email (email),
    UNIQUE KEY uq_patient_phone (phone)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- doctor
-- ---------------------------------------------------------------------
CREATE TABLE doctor (
    id        BIGINT       NOT NULL AUTO_INCREMENT,
    name      VARCHAR(100) NOT NULL,
    specialty VARCHAR(50)  NOT NULL,
    email     VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    phone     VARCHAR(10)  NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_doctor_email (email)
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- doctor_available_times: the slots a doctor publishes, one row each.
-- Generated by the @ElementCollection on Doctor.availableTimes.
-- ---------------------------------------------------------------------
CREATE TABLE doctor_available_times (
    doctor_id       BIGINT      NOT NULL,
    available_times VARCHAR(50) NOT NULL,
    KEY idx_dat_doctor (doctor_id),
    CONSTRAINT fk_dat_doctor FOREIGN KEY (doctor_id)
        REFERENCES doctor (id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------------------
-- appointment
-- status: 0 = scheduled, 1 = completed
-- Each appointment is one hour long; the end time is derived, not stored.
-- ---------------------------------------------------------------------
CREATE TABLE appointment (
    id               BIGINT   NOT NULL AUTO_INCREMENT,
    doctor_id        BIGINT   NOT NULL,
    patient_id       BIGINT   NOT NULL,
    appointment_time DATETIME NOT NULL,
    status           INT      NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_appointment_doctor (doctor_id),
    KEY idx_appointment_patient (patient_id),
    KEY idx_appointment_time (appointment_time),
    CONSTRAINT fk_appointment_doctor FOREIGN KEY (doctor_id)
        REFERENCES doctor (id) ON DELETE CASCADE,
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id)
        REFERENCES patient (id) ON DELETE CASCADE
) ENGINE=InnoDB;
